name: Verify project build

on:
  pull_request:
    branches:
      - forge/1.7.10
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Show debug info
        run: ./gradlew --version

      - name: Set up Interlink mod
        run: ./gradlew cleanCache clean setup --refresh-dependencies

      - name: Build Interlink mod
        run: ./gradlew build

